import type { Metadata } from "next"; // Importa o tipo Metadata de next para a tipagem dos metadados da página.
import localFont from "next/font/local"; // Importa a função localFont do Next.js para importar fontes locais.
import "./globals.css"; // Importa o arquivo global de estilos CSS.

const geistSans = localFont({
  src: "./fonts/GeistVF.woff", // Caminho para o arquivo de fonte local Geist Sans.
  variable: "--font-geist-sans", // Variável CSS personalizada para aplicar a fonte no site.
  weight: "100 900", // Define o intervalo de peso (espessura) da fonte (de 100 a 900).
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", // Caminho para o arquivo de fonte local Geist Mono.
  variable: "--font-geist-mono", // Variável CSS personalizada para aplicar a fonte no site.
  weight: "100 900", // Define o intervalo de peso (espessura) da fonte (de 100 a 900).
});

// Definindo os metadados da página
export const metadata: Metadata = {
  title: "Create Next App", // Título da página, exibido na aba do navegador.
  description: "Generated by create next app", // Descrição da página, usada por mecanismos de busca.
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-br"> {/* Define a linguagem da página como português brasileiro. */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // Aplica as fontes Geist Sans e Geist Mono usando variáveis CSS.
      >
        {children} {/* Renderiza o conteúdo da página dentro do layout */}
      </body>
    </html>
  );
}
